version: '3.8'

services:
  web:
    container_name: soal12
    build: .
    restart: always
    expose:
      - "80"
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=soal12.ctfai.my.id
      - LETSENCRYPT_HOST=soal12.ctfai.my.id
      - LETSENCRYPT_EMAIL=mzakifauzan77@gmail.com
    networks:
      - proxy-tier
    entrypoint: ["/wait-for-mysql.sh", "db", "apache2-foreground"]

  db:
    container_name: soal12-db
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - proxy-tier

volumes:
  db_data:

networks:
  proxy-tier:
    external: true
