version: '3.8'

services:
  web:
    container_name: simulasi-web-12
    build: .
    ports:
      - "8502:80"  
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    restart: always
    entrypoint: ["/wait-for-mysql.sh", "db", "apache2-foreground"]  # ⬅️ Tunggu DB siap

  db:
    container_name: simulasi-db-12
    image: mariadb:10.11
    restart: always
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db_data:
