version: '3.8'

services:
  web:
    build: .
    container_name: simulasi-web
    ports:
      - "8500:80"
    volumes:
      - .:/var/www/html
    restart: always  # ← INI yang bikin auto start saat reboot
