version: '3.8'

services:
  soal13:
    container_name: soal13-web
    build: .
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=soal13.ctfai.my.id
      - LETSENCRYPT_HOST=soal13.ctfai.my.id
      - LETSENCRYPT_EMAIL=mzakifauzan77@gmail.com
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true
